#!/bin/sh

set -e

# utilities

die () {
	echo "$*" >&2
	exit 1
}

# commands

build() {
	go build -o $1/main ./$1
}

dependents() {
	for P in $(ls -d */|grep -v vendor); do
		go list -f '{{range $_, $x := .Imports}}{{if eq $x "example.com/'$1'"}}'$P'{{end}}{{end}}' "./$P"
	done
}

# command switch

case $1 in
dependents)
	[[ -n $2 ]] || die "Usage: $0 dependents <project>"
	dependents $2
	;;
build)
	[[ -n $2 ]] || die "Usage: $0 build <project>"
	build $2
	;;
*)
	die "No such command: $1\nUsage: $0 <command> <opts>"
	;;
esac
